Fall2025-project3-jagrisaffe/Controllers/ActorsController.cs
using Fall2025_project3_jagrisaffe.Data;
using Fall2025_project3_jagrisaffe.Models;
using Fall2025_project3_jagrisaffe.Models.ViewModels;
using Fall2025_project3_jagrisaffe.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourProjectName.Services;

namespace Fall2025_project3_jagrisaffe.Controllers
{
    public class ActorsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAIService _aiService;
        private readonly ISentimentService _sentimentService;

        public ActorsController(ApplicationDbContext context, IAIService aiService, ISentimentService sentimentService)
        {
            _context = context;
            _aiService = aiService;
            _sentimentService = sentimentService;
        }

        public async Task<IActionResult> Photo(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var actor = await _context.Actor.FirstOrDefaultAsync(s => s.Id == id);

            if (actor == null || actor.Photo == null)
            {
                return NotFound();
            }

            return File(actor.Photo, "image/jpg");
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Actor.ToListAsync());
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor
                .Include(m => m.ActorMovies)
                    .ThenInclude(am => am.Movie)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (actor == null)
            {
                return NotFound();
            }

            var movies = await _context.ActorMovie
                .Include(m => m.Movie)
                .Where(m => m.ActorId == id)
                .Select(m => m.Movie!)
                .ToListAsync();

            // Generate tweets using AI
            var tweetTexts = await _aiService.GenerateActorTweets(actor.Name, 20);

            // Analyze sentiment for tweets
            var tweets = tweetTexts.Select(text => new TweetsWithSentiment
            {
                Text = text,
                SentimentScore = _sentimentService.AnalyzeSentiment(text)
            }).ToList();

            // Calculate average sentiment
            var averageSentiment = tweets.Any() ? tweets.Average(r => r.SentimentScore) : 0;

            var vm = new ActorDetailsViewModel()
            {
                Actor = actor,
                Movies = movies,
                Tweets = tweets,
                AverageSentiment = averageSentiment

            };

            return View(vm);
        }

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Gender,Age,IMDBLink")] Actor actor, IFormFile? Photo)
        {
            if (ModelState.IsValid)
            {
                if (Photo != null && Photo.Length > 0)
                {
                    using var stream = new MemoryStream();
                    await Photo.CopyToAsync(stream);
                    actor.Photo = stream.ToArray();
                }
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Gender,Age,IMDBLink")] Actor actor, IFormFile? Photo)
        {
            if (id != actor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (Photo != null && Photo.Length > 0)
                {
                    using var stream = new MemoryStream();
                    await Photo.CopyToAsync(stream);
                    actor.Photo = stream.ToArray();
                }
                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await _context.Actor.FindAsync(id);
            if (actor != null)
            {
                _context.Actor.Remove(actor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
            return _context.Actor.Any(e => e.Id == id);
        }
    }
}

Fall2025-project3-jagrisaffe/Controllers/MoviesController.cs
using Fall2025_project3_jagrisaffe.Data;
using Fall2025_project3_jagrisaffe.Models;
using Fall2025_project3_jagrisaffe.Models.ViewModels;
using Fall2025_project3_jagrisaffe.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourProjectName.Services;

namespace Fall2025_project3_jagrisaffe.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAIService _aiService;
        private readonly ISentimentService _sentimentService;

        public MoviesController(ApplicationDbContext context, IAIService aiService, ISentimentService sentimentService)

        {
            _context = context;
            _aiService = aiService;
            _sentimentService = sentimentService;
        }

        public async Task<IActionResult> Poster(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var movie = await _context.Movie.FirstOrDefaultAsync(s => s.Id == id);

            if (movie == null || movie.Poster == null)
            {
                return NotFound();
            }

            return File(movie.Poster, "image/jpg");
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Movie.ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .Include(m => m.ActorMovies)
                    .ThenInclude(am => am.Actor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            // Get the list of actors
            var actors = movie.ActorMovies.Select(am => am.Actor).ToList();

            // Generate reviews using AI
            var reviewTexts = await _aiService.GenerateMovieReviews(movie.Title, 10);

            // Analyze sentiment for each review
            var reviews = reviewTexts.Select(text => new ReviewWithSentiment
            {
                Text = text,
                SentimentScore = _sentimentService.AnalyzeSentiment(text)
            }).ToList();

            // Calculate average sentiment
            var averageSentiment = reviews.Any() ? reviews.Average(r => r.SentimentScore) : 0;

            var viewModel = new MovieDetailsViewModel
            {
                Movie = movie,
                Actors = actors,
                Reviews = reviews,
                AverageSentiment = averageSentiment
            };

            return View(viewModel);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,IMDBLink,Year,Genre")] Movie movie, IFormFile? Poster)
        {

            if (ModelState.IsValid)
            {
                if(Poster != null && Poster.Length > 0)
                {
                    using var stream = new MemoryStream();
                    await Poster.CopyToAsync(stream);
                    movie.Poster = stream.ToArray();
                }
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,IMDBLink,Year,Genre")] Movie movie, IFormFile? Poster)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (Poster != null && Poster.Length > 0)
                {
                    using var stream = new MemoryStream();
                    await Poster.CopyToAsync(stream);
                    movie.Poster = stream.ToArray();
                }
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.FindAsync(id);
            if (movie != null)
            {
                _context.Movie.Remove(movie);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.Id == id);
        }
    }
}

Fall2025-project3-jagrisaffe/Views/Movies/Create.cshtml
@model Fall2025_project3_jagrisaffe.Models.Movie

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IMDBLink" class="control-label"></label>
                <input asp-for="IMDBLink" class="form-control" />
                <span asp-validation-for="IMDBLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poster" class="control-label"></label>
                <input type="file" name="Poster" class="form-control" />
                <span asp-validation-for="Poster" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <input type="submit" value="Create" class="btn btn-primary btn-lg" />
            </div>
        </form>
    </div>
</div>

<div class="mt-3">
    <a asp-action="Index" class="btn btn-secondary-custom">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fall2025-project3-jagrisaffe/Views/Movies/Delete.cshtml
@model Fall2025_project3_jagrisaffe.Models.Movie

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IMDBLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IMDBLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poster)
        </dt>
        <dd class="col-sm-10">
            @if (Model.Poster != null)
            {
                var base64 = Convert.ToBase64String(Model.Poster);
                var imgSrc = $"data:image/jpeg;base64,{base64}";
                <img src="@imgSrc" alt="@Model.Title poster" style="max-width: 180px; max-height: 150px;"  />
            }
            else
            {
                <div class="alert alert-secondary">No poster available</div>
            }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Fall2025-project3-jagrisaffe/Views/Movies/Details.cshtml
@model Fall2025_project3_jagrisaffe.Models.ViewModels.MovieDetailsViewModel

@{
    ViewData["Title"] = "Movie Details";
}

<h1>@Model.Movie.Title</h1>

<div class="row">
    <div id="photo-container" class="col-md-4">
        @if (Model.Movie.Poster != null)
        {
            var base64 = Convert.ToBase64String(Model.Movie.Poster);
            var imgSrc = $"data:image/jpeg;base64,{base64}";
            <img src="@imgSrc" alt="@Model.Movie.Title poster" class="img-fluid rounded" />
        }
        else
        {
            <div class="alert alert-secondary">No poster available</div>
        }
    </div>

    <div class="col-md-8">
        <dl class="row">
            <dt class="col-sm-3">Genre</dt>
            <dd class="col-sm-9">@Model.Movie.Genre</dd>

            <dt class="col-sm-3">Year</dt>
            <dd class="col-sm-9">@Model.Movie.Year</dd>

            <dt class="col-sm-3">IMDB</dt>
            <dd class="col-sm-9">
                <a href="@Model.Movie.IMDBLink" target="_blank" rel="noopener noreferrer">View on IMDB</a>
            </dd>
        </dl>

        <h3>Actors in this Movie</h3>
        @if (Model.Actors.Any())
        {
            <ul class="list-group mb-4">
                @foreach (var actor in Model.Actors)
                {
                    <li class="list-group-item">
                        <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id">
                            @actor.Name
                        </a>
                    </li>
                }
            </ul>
        }
        else
        {
            <p class="text-muted">No actors assigned yet.</p>
        }

        <div class="mt-4">
            <a asp-action="Edit" asp-route-id="@Model.Movie.Id" class="btn btn-warning">Edit</a>
            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            <a asp-action="Delete" asp-route-id="@Model.Movie.Id" class="btn btn-danger">Delete</a>
        </div>
    </div>
</div>

<hr class="my-4" />

<h2>AI Generated Reviews</h2>

@if (Model.Reviews.Any())
{
    <h4>
        Average Sentiment:
        <span class="badge @(Model.AverageSentiment >= 0.05 ? "bg-success" : Model.AverageSentiment <= -0.05 ? "bg-danger" : "bg-secondary")">
            @Model.AverageSentiment.ToString("F2")
        </span>
    </h4>

    <table id="reviews-table" class="table table-striped mt-3">
        <thead>
            <tr>
                <th style="width: 70%">Review</th>
                <th style="width: 30%">Sentiment Score</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var review in Model.Reviews)
            {
                <tr>
                    <td>@review.Text</td>
                    <td>
                        <span class="badge @(review.SentimentScore >= 0.05 ? "bg-success" : review.SentimentScore <= -0.05 ? "bg-danger" : "bg-secondary")">
                            @review.SentimentScore.ToString("F2")
                        </span>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p class="text-muted">No reviews generated yet.</p>
}
@section Scripts {
    <script>
        $(document).ready(function() {
            $('#reviews-table').DataTable({
                "paging": true,
                "searching": true,
                "ordering": true,
                "order": [[1, "asc"]],
            });
        });
    </script>
}

Fall2025-project3-jagrisaffe/Views/Movies/Edit.cshtml
@model Fall2025_project3_jagrisaffe.Models.Movie

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IMDBLink" class="control-label"></label>
                <input asp-for="IMDBLink" class="form-control" />
                <span asp-validation-for="IMDBLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poster" class="control-label"></label>
                <input type="file" name="Poster" class="form-control" />
                <span asp-validation-for="Poster" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fall2025-project3-jagrisaffe/Views/Movies/Index.cshtml
@model IEnumerable<Fall2025_project3_jagrisaffe.Models.Movie>

@{
    ViewData["Title"] = "Index";
}

<h1>Movie Collection</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Add Movie</a>
</p>
<table id="movies" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IMDBLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poster)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td style="font-weight: 500;">
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <a href="@item.IMDBLink" target="_blank">View on IMDB</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
                <td>
                    @if (item.Poster != null)
                    {
                        var base64 = Convert.ToBase64String(item.Poster);
                        var imgSrc = $"data:image/jpeg;base64,{base64}";
                        <img src="@imgSrc" alt="@item.Title poster" style="max-width: 50px; max-height: 75px;" />
                    }
                    else
                    {
                        <span class="text-muted">No poster</span>
                    }
                </td>
                <td>
                    <div class="btn-group" role="group">
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">Details</a>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                    </div>
                </td>
        </tr>
}
    </tbody>
</table>
@section Scripts {
    <script>
        $(document).ready(function() {
            $('#movies').DataTable({
                "paging": true,
                "searching": true,
                "ordering": true,
                "order": [[1, "asc"]],
                "columnDefs": [
                    { "orderable": false, "targets": [1, 4] } // Poster column
                ]
            });
        });
    </script>
}